In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
data = sns.load_dataset('titanic')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
snippet = data.head(50)
print(snippet)

In [ ]:
data.pivot_table('survived', index='sex', columns='class')

In [ ]:
print(type(np.sumd))

In [ ]:
def sumd(x):
    print("1st percentile:", np.nanpercentile(x, 1))
    print("5th percentile:", np.nanpercentile(x, 5))
    print("25th percentile:", np.nanpercentile(x, 25))
    print("50th percentile:", np.nanpercentile(x, 50))
    print("75th percentile:", np.nanpercentile(x, 75))
    print("90th percentile:", np.nanpercentile(x, 90))
    print("95th percentile:", np.nanpercentile(x, 95))
    print("99th percentile:", np.nanpercentile(x, 99))
    print("mean:", np.nanmean(x))
    print("Std. Dev.", np.std(x))
    print("n:", len(x))

In [ ]:
sumd(data['age'])

In [ ]:
data.head()

In [10]:
a = np.arange(3).reshape((3, 1))

In [11]:
a

array([[0],
       [1],
       [2]])

In [12]:
b = np.arange(3)
b

array([0, 1, 2])

In [19]:
c = np.arange(3).reshape(1, 3)
c

array([[0, 1, 2]])